CREATE TABLE `taskDefinitions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taskId` varchar(100) NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`sectionId` varchar(50),
	`sectionTitle` varchar(255),
	`sectionDuration` varchar(50),
	`swimLanes` json,
	`dependsOn` json,
	`sortOrder` int NOT NULL DEFAULT 0,
	`intakeLink` varchar(500),
	`intakeLinkLabel` varchar(255),
	`specLink` varchar(500),
	`specLinkLabel` varchar(255),
	`isActive` tinyint NOT NULL DEFAULT 1,
	`notionPageId` varchar(64),
	`notionLastEdited` timestamp,
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `taskDefinitions_id` PRIMARY KEY(`id`),
	CONSTRAINT `taskDefinitions_taskId_unique` UNIQUE(`taskId`)
);
